// capsuleRegistry.js
// VaultiqX Capsule Registry — lineage anchors and fusion status

const capsuleRegistry = [
  {
    id: "C001",
    route: "/public",
    title: "Public Access Capsule",
    fusion: true,
    anchors: [
      "eternumReady",
      "originumProtected",
      "divinumBound",
      "infinitumTrace",
      "anantumVow",
      "vasthavumSnapshot",
      "pranavaTrace",
      "quantumEnabled",
      "sovereignAIEnabled",
    ],
    lastUpdated: "2025-11-22",
  },
  {
    id: "C002",
    route: "/govtech",
    title: "GovTech Dashboard",
    fusion: true,
    anchors: [
      "eternumReady",
      "originumProtected",
      "divinumBound",
      "quantumEnabled",
      "sovereignAIEnabled",
    ],
    lastUpdated: "2025-11-22",
  },
  {
    id: "C003",
    route: "/rituals",
    title: "Governance Ritual Engine",
    fusion: true,
    anchors: [
      "eternumReady",
      "originumProtected",
      "infinitumTrace",
      "quantumEnabled",
      "sovereignAIEnabled",
    ],
    lastUpdated: "2025-11-22",
  },
  {
    id: "C004",
    route: "/escalation",
    title: "Sovereign Escalation Grid",
    fusion: true,
    anchors: [
      "eternumReady",
      "vasthavumSnapshot",
      "pranavaTrace",
      "quantumEnabled",
      "sovereignAIEnabled",
    ],
    lastUpdated: "2025-11-22",
  },
  {
    id: "C005",
    route: "/registry",
    title: "Capsule Trace Viewer",
    fusion: true,
    anchors: [
      "eternumReady",
      "originumProtected",
      "divinumBound",
      "infinitumTrace",
      "anantumVow",
      "vasthavumSnapshot",
      "pranavaTrace",
      "quantumEnabled",
      "sovereignAIEnabled",
    ],
    lastUpdated: "2025-11-22",
  },
  {
    id: "C006",
    route: "/license-upgrade",
    title: "License Upgrade Capsule",
    fusion: true,
    anchors: [
      "eternumReady",
      "originumProtected",
      "divinumBound",
      "quantumEnabled",
      "sovereignAIEnabled",
    ],
    lastUpdated: "2025-11-22",
  },
  {
    id: "C007",
    route: "/founder-appointment",
    title: "Founder Appointment Capsule",
    fusion: true,
    anchors: [
      "eternumReady",
      "originumProtected",
      "infinitumTrace",
      "anantumVow",
      "quantumEnabled",
      "sovereignAIEnabled",
    ],
    lastUpdated: "2025-11-22",
  },
  {
    id: "C008",
    route: "/tribute-game",
    title: "Tribute Game Capsule",
    fusion: true,
    anchors: [
      "eternumReady",
      "originumProtected",
      "vasthavumSnapshot",
      "pranavaTrace",
      "quantumEnabled",
      "sovereignAIEnabled",
    ],
    lastUpdated: "2025-11-22",
  },
];

export default capsuleRegistry;